include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/**/*.gr.dart'
    - 'lib/**/*.g.dart'
linter:
  rules:
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
