name: vienna
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  collection: ^1.18.0
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.0+2
  flutter_secure_storage: ^4.2.1
  get_it: ^7.6.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  mobx: ^2.3.0+1
  path_provider: ^2.1.2
  retrofit: ^4.0.3
  sqflite: ^2.3.2
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  mobx_codegen: ^2.6.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
